#define HOMER_template
#homer$(1): $(SDSS_HOMER)sdssfield$(1)-homer.xy.fits
#homer: homer$(1)
#$(SDSS_HOMER)sdssfield$(1)-homer.xy.fits: $(SDSS_FIELDS)sdssfield$(1).xy.fits
#	-$(MKDIR) $(SDSS_HOMER)
#	$(HOMER) -i $$< -o $$@.tmp $(HOMER_OPTS)
#	$(MV) $$@.tmp $$@
#endef
#FN := 01 02 03 04 05 06 07 08 09 10 \
#	  11 12 13 14 15 16 17 18 19 20 \
#	  21 22 23 24 25 26 27 28 29 30 \
#	  31 32 33 34 35
#$(foreach num,$(FN),$(eval $(call HOMER_template,$(num))))

