#! /bin/bash

if [ $# -lt 2 ]; then
  echo "Usage: $0 <header-file> <file1> [<file2> <...>]"
  exit -1;
fi

HDR="$1"
shift

while [ $# -gt 0 ]; do
  FN="$1"
  TMPFN="tmp.$FN"
  echo "$FN"
  cat "$HDR" "$FN" > "$TMPFN"
  mv "$TMPFN" "$FN"
  shift
done

