#! /bin/bash

for ((i=1; i<=35; i++)); do
  in=`printf sdssfield%02i.fits $i`
  out=`printf sdssfield%02i.rd.fits $i`
  cmd="subtable -c RA -c DEC -i $in -o $out"
  echo $cmd
  $cmd >> rd.log 2>&1
done

