#! /bin/bash

for ((i=1; i<=35; i++)); do
  in=`printf sdssfield%02i.fits $i`
  out=`printf sdssfield%02i.xy.fits $i`
  cmd="subtable -c ROWC -c COLC -i $in -o $out"
  echo $cmd
  $cmd >> xy.log 2>&1
done

