#! /bin/bash

for x in u g r i z; do
  for ((i=1; i<=40; i++)); do
    in=`printf sdssfield_$x%02i.fits $i`
    out=`printf sdssfield_$x%02i.rd.fits $i`
    cmd="subtable -c ROWC -c COLC -i $in -o $out"
    echo $cmd
    $cmd >> xy.log 2>&1
  done
done

