#! /bin/bash

# Reduce the size of SDSS xy list files by:
#  -converting from "D" (double) to "E" (float) format
#  -keeping only the first 150 rows

# Also changes the column names from "COLC, ROWC" to "X, Y".

if [ $# -lt 2 ]; then
	echo "Usage: $0 <in> <out> [#rows]"
	exit
fi
in=$1
out=$2
if [ $# -eq 3 ]; then
  n=$3
fi

TMPDIR=`mktemp -d /tmp/tmp.reduce-size.XXXXXX`
echo "Placing temp files in $TMPDIR"

for ((e=1;; e++)); do
	E=`printf %04i $e`
	fitsgetext -i $in -o $TMPDIR/A$e -e 0 -e $e
	if [ $? -ne 0 ]; then
		break;
	fi
	rm -f $TMPDIR/B$E
	if [ x$n != x ]; then
		fitscopy $TMPDIR/A$e"[col X(1E)=COLC;Y(1E)=ROWC][#row<=$n]" $TMPDIR/B$E
	else
		fitscopy $TMPDIR/A$e"[col X(1E)=COLC;Y(1E)=ROWC]" $TMPDIR/B$E
	fi
	mv $TMPDIR/B$E $TMPDIR/A$e
	fitsgetext -i $TMPDIR/A$e -o $TMPDIR/B$E -e 1
	rm $TMPDIR/A$e
done
fitsgetext -i $in -o $TMPDIR/B0000 -e 0
cat $TMPDIR/B* > $out
rm $TMPDIR/B*
rmdir $TMPDIR
