#! /bin/bash

# Reduce the size of SDSS xy list files by:
#  -converting from "D" (double) to "E" (float) format
#  -keeping only the first N rows

# Also changes the column names from "COLC, ROWC" to "X, Y".

if [ $# -lt 2 ]; then
	echo "Usage: $0 <in> <out> [#rows]"
	exit
fi
in=$1
out=$2
if [ $# -eq 3 ]; then
  n=$3
fi

TMPDIR=`mktemp -d /tmp/tmp.reduce-size.XXXXXX`
echo "Placing temp files in $TMPDIR"

fitsgetext -i $in -o $TMPDIR/ext%05i -a
if [ $? -ne 0 ]; then
	echo "fitsgetext failed.";
	exit -1;
fi

shopt -s nullglob    # If no match, filename expands to nothing.
EXTS=( $TMPDIR/ext* )
EXT0=${EXTS[0]}
#EXT0="$TMPDIR/ext00000"

#echo "ext0: $EXT0"
#echo "extensions: ${EXTS[*]}"

for ((i=1; i<${#EXTS[*]}; i++)); do
	echo "processing extension $i of ${#EXTS[*]}"
	e="${EXTS[$i]}"
	cat $EXT0 $e > $TMPDIR/E
	if [ x$n != x ]; then
		fitscopy $TMPDIR/E"[col X(1E)=COLC;Y(1E)=ROWC][#row<=$n]" $TMPDIR/O
	else
		fitscopy $TMPDIR/E"[col X(1E)=COLC;Y(1E)=ROWC]" $TMPDIR/O
	fi
	fitsgetext -i $TMPDIR/O -o $TMPDIR/out.`basename $e` -e 1 > /dev/null
	rm $TMPDIR/O
done
cat $EXT0 $TMPDIR/out.* > $out
rm -R $TMPDIR

exit 0;
