#! /bin/bash

if [ $# -ne 3 ]; then
	echo "Usage: $0 <original .fits file> <in.xy.fits> <out.xy.fits>"
	exit
fi
id=$1
in=$2
out=$3

TMPDIR=`mktemp -d /tmp/tmp.sdss-fieldid.XXXXXX`
echo "Placing temp files in $TMPDIR"

fitsgetext -i $id -o $TMPDIR/id.%05i -a
if [ $? -ne 0 ]; then
	echo "fitsgetext on id failed.";
	exit -1;
fi
fitsgetext -i $in -o $TMPDIR/in.%05i -a
if [ $? -ne 0 ]; then
	echo "fitsgetext on input failed.";
	exit -1;
fi

shopt -s nullglob    # If no match, filename expands to nothing.
EXTS=( $TMPDIR/id.* )
EXT0="${EXTS[0]}"
INEXTS=( $TMPDIR/in.* )
INEXT0="${INEXTS[0]}"

for ((i=1; i<${#EXTS[*]}; i++)); do
	echo "processing extension $i of ${#EXTS[*]}"
	e="${EXTS[$i]}"
	cat $EXT0 $e > $TMPDIR/E
	ID=`tablist $TMPDIR/E"[1][#row==1][col RUN;RERUN;CAMCOL;FIELD;FILTER]" | awk 'BEGIN{OFS="-"} {if (NF==6) print "SDSS",$2,$3,$4,$5,$6}'`
	echo "ID $ID"
	e="${INEXTS[$i]}"
	cat $INEXT0 $e > $TMPDIR/I
	modhead $TMPDIR/I"[1]" FIELDID "$ID"
	I=`printf %05i $i`
	fitsgetext -i $TMPDIR/I -o $TMPDIR/out.$I -e 1 > /dev/null
done
L=( $INEXT0 $TMPDIR/out.* );
echo "${L[*]}" | xargs -n 50 cat > $out
rm -R $TMPDIR

exit 0;
