#! /bin/bash

if [ $# -ne 2 ]; then
	echo "Usage: $0 <in> <out>"
	exit
fi
in=$1
out=$2

TMPDIR=`mktemp -d /tmp/tmp.sdss-fieldid.XXXXXX`
echo "Placing temp files in $TMPDIR"

fitsgetext -i $in -o $TMPDIR/in.%05i -a
if [ $? -ne 0 ]; then
	echo "fitsgetext failed.";
	exit -1;
fi

shopt -s nullglob    # If no match, filename expands to nothing.
EXTS=( $TMPDIR/in.* )
EXT0="${EXTS[0]}"

for ((i=1; i<${#EXTS[*]}; i++)); do
	echo "processing extension $i of ${#EXTS[*]}"
	e="${EXTS[$i]}"
	cat $EXT0 $e > $TMPDIR/E
	ID=`tablist $TMPDIR/E"[1][#row==1][col RUN;RERUN;CAMCOL;FIELD;FILTER]" | awk 'BEGIN{OFS="-"} {if (NF==6) print "SDSS",$2,$3,$4,$5,$6}'`
	echo "ID $ID"
	modhead $out"[$i]" FIELDID "$ID"
done
rm -R $TMPDIR

exit 0;
