#! /bin/bash

if [ $# -ne 1 ]; then
	echo "Usage: $0 <user-email-address>"
    exit
fi
USER="$1"
HOST=`hostname`
if [ $HOST != astrometry ]; then
    echo "This script must be run on astrometry.net"
    exit
fi
# is this user part of the "list" group?
GR=`groups`
echo $GR | grep "\<list\>"
if [ $? -ne 0 ]; then
    echo "You must be a member of the unix group \"list\"."
    echo "You are a member of groups: $GR"
    exit
fi

cd /var/lib/mailman/bin && echo $USER | ./add_members --regular-members-file - \
    --welcome-msg n --admin-notify n astrometry-users

