#! /bin/bash

# This script gets run via ssh from oven.

# Careful about writing things to stdout - we pipe it to tar on the other end.

# Read jobid
read -s jobid

# Replace "-" by "/".
jobid=`echo "$jobid" | sed s+-+/+g`

# Create our job directory.
cd /nobackup/stars/ontheweb-data
mkdir -p $jobid
cd $jobid
tar xf -

# Index path replacement.
sed s+/home/gmaps/ontheweb-indexes+/nobackup/stars/INDEXES+ < input > input.c27

# stderr goes back over the ssh tunnel to the log file on oven.
~/amd-an/quads/blind < input.c27 > blind.stdout

# Send back all the files we generated!
tar cf - *
