#!/bin/bash

FBASE=/home/dstn
IBASE=/home/dstn

HPORDER="2 1 6 4 5 7 0 3 8 11 10 9"

TMP=/scr/dstn/
INDEXSRC=$IBASE/INDEXES/sdss-hp-7/ddd_%02i
INDEX=$TMP/sdss-hp-7/ddd_%02i

FIELD=$FBASE/SDSS_FIELDS/sdssfield01
FIELDID=1

THREADS=1

XCOL=ROWC
YCOL=COLC
PARITY=1
SDEPTH=0
DEPTH=80

FUL=0.38
FUU=0.42
TOL=0.01

NAGREE=4
AGREETOL=10
DO_CORRESPOND=0

DONUT_DIST=4
DONUT_THRESH=0.5

VERIFY_DIST=3
NAGREE_TOVERIFY=2
OVERLAP_TOSOLVE=0.5
OVERLAP_TOKEEP=0.2
MIN_NINFIELD=50

INPUT=input.%03i
MATCH=agree.%03i
DONE=done.%03i
SOLVED=solved.%04i

filenum=-1

for ((f=0; f<10; f++)); do
        for ((h=0; h<12; h++)); do

		cmd="{print \$$(($h+1))}"
		i=`echo $HPORDER | gawk "$cmd"`

                start=$(($f * 1000))
                end=$((($f+1) * 1000 - 1))

                index=`printf $INDEX $i`
                indexsrc=`printf $INDEXSRC $i`

                filenum=$((filenum +1))
                filename=`printf $INPUT $filenum`
                echo $filename
                match=`printf $MATCH $filenum`
                done=`printf $DONE $filenum`

                flds="${start}/${end}"

                txt="index ${index}\n"
                txt="${txt}index_src ${indexsrc}\n"
                txt="${txt}field $FIELD\n"
		txt="${txt}fieldid $FIELDID\n"
                txt="${txt}xcol $XCOL\n"
                txt="${txt}ycol $YCOL\n"
                txt="${txt}match ${match}\n"
                txt="${txt}done $done\n"
                txt="${txt}fields ${flds}\n"
                txt="${txt}sdepth $SDEPTH\n"
                txt="${txt}depth $DEPTH\nparity $PARITY\ntol $TOL\n"
                if [ x$FUL != x ]; then
                        txt="${txt}fieldunits_lower $FUL\n"
                fi
                if [ x$FUU != x ]; then
                        txt="${txt}fieldunits_upper $FUU\n"
                fi
                if [ x$SOLVED != x ]; then
                        txt="${txt}solved $SOLVED\n"
                fi
                txt="${txt}nagree $NAGREE\n"
                txt="${txt}agreetol $AGREETOL\n"
				if [ x$MAXNAGREE != x ]; then
					txt="${txt}maxnagree $MAXNAGREE\n"
				fi
		if [ x$DONUT_DIST != x ]; then
		    txt="${txt}donut_dist $DONUT_DIST\n"
		    txt="${txt}donut_thresh $DONUT_THRESH\n"
		fi

                if [ x$VERIFY_DIST != x ]; then
					txt="${txt}verify_dist $VERIFY_DIST\n"
					txt="${txt}nagree_toverify $NAGREE_TOVERIFY\n"
					txt="${txt}overlap_tosolve $OVERLAP_TOSOLVE\n"
					txt="${txt}overlap_tokeep $OVERLAP_TOKEEP\n"
					txt="${txt}min_ninfield $MIN_NINFIELD\n"
				fi
                txt="${txt}do_correspond $DO_CORRESPOND\n"
		txt="${txt}threads $THREADS\n"
                txt="${txt}run\n"
                echo -n -e $txt > $filename
        done
done


