#!/bin/bash

# This script is used to generate indexes out of Healpix-ified catalogues.
# Run it like   "script 0 1 2 3 4 5" to generate catalogues zero through 5.

echo "Args: $*"

# The filename of the original catalogues.
CATALOGUE=/p/learning/stars/CATALOGUES/an-sdss-dd/an-sdss-dd_%02i

# The filename of the index.
INDEX=index_%02i

# The filename of the deduplicated index.
INDEX_DEDUP=ddind_%02i

# The filename of the unpermuted index.
INDEX_UNPERM=sdss-8_%02i

# quad scale (arcmin)
SCALE="-l 4 -u 5"

# nside, index ID
HPQUADS="-n 705 -i 8"

# codetree options
CTOPTS="-R 15"

for i in $@; do
	# Input files:
	IN=`printf $CATALOGUE $i`
	echo source catalogue is $IN

	FN=`printf $INDEX $i`
	echo first-stage index is $FN

	if [ -e $FN.code.fits ] && [ -e $FN.quad.fits ]; then
		echo Code and quad files already exist:
		echo     $FN.code.fits
		echo     $FN.quad.fits
	else
		CMD="hpquads $HPQUADS $SCALE -f $IN -o $FN"
		echo Running: $CMD
		time $CMD  ||  continue
	fi

	DD=`printf $INDEX_DEDUP $i`
	echo de-duplicated index is $DD

	if [ -e $DD.code.fits ] && [ -e $DD.quad.fits ]; then
		echo Code and quad files already exist:
		echo     $DD.code.fits
		echo     $DD.quad.fits
	else
		CMD="dedup_index -f $FN -o $DD"
		echo Running: $CMD
		time $CMD  ||  continue
	fi

	if [ -e $DD.ckdt.fits ]; then
		echo Code kdtree already exists:
		echo     $DD.ckdt.fits
	else
		echo Generating code tree...
		CMD="codetree $CTOPTS -f $DD -o $DD"
		echo Running: $CMD
		time $CMD  ||  continue
	fi

	UP=`printf $INDEX_UNPERM $i`
	echo unpermuted index is $UP

	if [ -e $UP.ckdt.fits ] && [ -e $UP.quad.fits ]; then
		echo ckdt and quad files already exist:
		echo     $UP.ckdt.fits
		echo     $UP.quad.fits
	else
		CMD="unpermute-quads -f $DD -o $UP"
		echo Running: $CMD
		time $CMD  ||  continue
	fi

	if [ -e $UP.skdt.fits ]; then
		echo -n;
	else
		CMD="ln -s $IN.skdt.fits $UP.skdt.fits"
		echo Running: $CMD
		$CMD  ||  continue
	fi

done

