#!/bin/bash

if [ $# -lt 1 ]; then
  echo
  echo "Usage: $0 <input-file.eps> [output-file.png]"
  echo
  exit
fi

IN=$1

if [ $# -eq 2 ]; then
  OUT=$2
else
  OUT=`basename $IN .eps`.png
fi

#echo IN $IN
#echo OUT $OUT

#pstopnm -portrait -stdout $IN | pnmtopng > $OUT

#BBOX=`gs -q -dNOPAUSE -dBATCH -dSAFER -dTextAlphaBits=4 \
#	-dGraphicsAlphaBits=4 -sDEVICE=bbox $IN 2>&1`

BBOX=`grep %%BoundingBox $IN`

echo bbox $BBOX

XL=`echo $BBOX | grep "%%BoundingBox" | gawk '{print $2}'`
YL=`echo $BBOX | grep "%%BoundingBox" | gawk '{print $3}'`
XU=`echo $BBOX | grep "%%BoundingBox" | gawk '{print $4}'`
YU=`echo $BBOX | grep "%%BoundingBox" | gawk '{print $5}'`

echo X $XL -- $XU
echo Y $YL -- $YU

W=$(($XU - $XL))
H=$(($YU - $YL))

echo W $W
echo H $H

TMP=`mktemp /tmp/epstopng.XXXXXX`

gs -q -dNOPAUSE -dBATCH -dSAFER -dTextAlphaBits=4 \
	-dGraphicsAlphaBits=4 -sDEVICE=png16m \
	-sOutputFile=$TMP -g${XU}x${YU} $IN

echo "pngtopnm $TMP | pnmcut -l $XL -b $H | pnmtopng \> $OUT"
pngtopnm $TMP | pnmcut -l $XL -b $H | pnmtopng > $OUT

rm $TMP
