#! /bin/bash

if [ $# -eq 0 ]; then
  echo "usage: $0 <filename>"
  exit
fi

#LEN=`ls -s --block-size=1 $1 | awk '{print $1}'`
LEN=`ls -l $1 | awk '{print $5}'`
if [ "x$LEN" == "x" ]; then
  exit
fi
echo "File length $LEN"
if [ $(($LEN % 2880)) -eq 0 ]; then
  exit
else
  PAD=$((2880 - $LEN % 2880))
  echo "Adding $PAD bytes"
  dd bs=1 if=/dev/zero of=$1 seek=$LEN count=$PAD
fi

