#!/bin/bash

if [ "$*" == "" ]; then
	echo
	echo "Usage: makeobjlinks <source-filename-template>"
	echo "     (without the ##.objs suffix)"
	echo
	exit
fi

SRC=$1

for ((i=0; i<12; i++)); do
	PREFIX=`printf $SRC%02i $i`
	SRCFILE=$PREFIX.objs
	echo ln -s $SRCFILE .
	ln -s $SRCFILE .
done
