#! /bin/bash

# pictures of the deduplicated catalogs:
for x in 00 01 02 03 04 05 06 07 08 09 10 11; do
  plotcat -N 300 -h ../dd_${x}.objs.fits > dd${x}.pgm;
done
# their sum image:
b=dd
pnmarith -add ${b}00.pgm ${b}01.pgm > sum.pgm
for x in 02 03 04 05 06 07 08 09 10 11; do
  pnmarith -add sum.pgm ${b}${x}.pgm > sum-tmp.pgm
  mv sum-tmp.pgm sum.pgm
done
pnmtopng sum.pgm > sum-small.png
mv sum-small.png ddsum.png

# pictures of the quads we generate:
for x in 00 01 02 03 04 05 06 07 08 09 10 11; do
  quadlocations -n 300 -o quads${x}.pgm -f ../dd_${x} ;
done
# their sum image:
b=quads
pnmarith -add ${b}00.pgm ${b}01.pgm > sum.pgm
for x in 02 03 04 05 06 07 08 09 10 11; do
  pnmarith -add sum.pgm ${b}${x}.pgm > sum-tmp.pgm ;
  mv sum-tmp.pgm sum.pgm ;
done
pnmtopng sum.pgm > quadsum.png

# after deduplication, the quads:
for x in 00 01 02 03 04 05 06 07 08 09 10 11; do
  quadlocations -n 300 -o ddd${x}.pgm -f ../ddd_${x} ;
  pnmtopng ddd${x}.pgm > ddd${x}.png ;
done
# their sum image:
b=ddd
pnmarith -add ${b}00.pgm ${b}01.pgm > sum.pgm
for x in 02 03 04 05 06 07 08 09 10 11; do
  pnmarith -add sum.pgm ${b}${x}.pgm > sum-tmp.pgm ;
  mv sum-tmp.pgm sum.pgm ;
done
pnmtopng sum.pgm > dddsum.png

