#! /bin/bash

IN=$1
OUT=$2

N1=`modhead $IN NAXIS1 | gawk '{print $3}'`
N2=`modhead $IN NAXIS2 | gawk '{print $3}'`
BP=`modhead $IN BITPIX | gawk '{print $3}'`

rm a.fits b.fits c.fits d.fits
imcopy $IN"[1:$N1:2,1:$N2:2]" a.fits  || exit
imcopy $IN"[1:$N1:2,2:$N2:2]" b.fits  || exit
imcopy $IN"[2:$N1:2,1:$N2:2]" c.fits  || exit
imcopy $IN"[2:$N1:2,2:$N2:2]" d.fits  || exit
rm $OUT
if [ $BP -ne 32 ]; then
    rm aa.fits bb.fits cc.fits dd.fits aabb.fits ccdd.fits
    iofits a.fits aa.fits 32  || exit
    iofits b.fits bb.fits 32  || exit
    iofits c.fits cc.fits 32  || exit
    iofits d.fits dd.fits 32  || exit
    imarith aa.fits bb.fits a aabb.fits  || exit
    imarith cc.fits dd.fits a ccdd.fits  || exit
    imarith aabb.fits ccdd.fits a $OUT  || exit
else
    rm ab.fits cd.fits
    imarith a.fits b.fits a ab.fits  || exit
    imarith c.fits d.fits a cd.fits  || exit
    imarith ab.fits cd.fits a $OUT  || exit
fi
