#! /bin/bash

# base name of log file.
#LOGBASE=$1
#shift

# base name of log file.
if [ -z $LOG_BASE ]; then
  LOG_BASE=log-
fi

# find name of executable to run
EXE=$1

EXENAME=`basename $EXE`

# logfile name
DATE=`date`
for ((i=1;; i++)); do
  LOGFILE="$LOG_BASE-$EXENAME-$i"
  if [ -e $LOGFILE ]; then
	echo "File $LOGFILE exists";
  else
    break;
  fi
done

echo "Writing to log file $LOGFILE"
echo "an-run: logging command: $@" > $LOGFILE

$@ 2>&1 | tee -a $LOGFILE
