#! /bin/bash

# find name of executable to run
EXE=$1

EXENAME=`basename $EXE`

# logfile name
DATE=`date`
for ((i=1;; i++)); do
  LOGFILE="log-$EXENAME-$i"
  if [ -e $LOGFILE ]; then
	echo "File $LOGFILE exists";
  else
    break;
  fi
done

echo "Writing to log file $LOGFILE"
echo "an-run: logging command: $@" > $LOGFILE

$@ 2>&1 | tee -a $LOGFILE
