#! /bin/bash

# This file is part of the Astrometry.net suite.
# Copyright 2006, Dustin Lang, Keir Mierle and Sam Roweis.
#
# The Astrometry.net suite is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, version 2.
#
# The Astrometry.net suite is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Astrometry.net suite ; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

# base name of log file.
if [ -z $LOG_BASE ]; then
  LOG_BASE=log
fi

# find name of executable to run
EXE=$1

EXENAME=`basename $EXE`

# logfile name
DATE=`date`
for ((i=1;; i++)); do
  LOGFILE="$LOG_BASE-$EXENAME-$i"
  if [ -e $LOGFILE ]; then
	echo "File $LOGFILE exists";
  else
    break;
  fi
done

echo "Writing to log file $LOGFILE"
echo "an-run: logging command: $@" > $LOGFILE

$@ 2>&1 | tee -a $LOGFILE
