#! /bin/bash

# This file is part of the Astrometry.net suite.
# Copyright 2006, Dustin Lang, Keir Mierle and Sam Roweis.
#
# The Astrometry.net suite is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, version 2.
#
# The Astrometry.net suite is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Astrometry.net suite ; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

FBASE=sdss-fields
IBASE=.

HPORDER="2 1 6 4 5 7 0 3 8 11 10 9"

INDEX=$IBASE/sdss-1/sdss-1-%02i
FIELD_TEMPLATE=$FBASE/sdssfield%02i-hp02.xy

XCOL=X
YCOL=Y
PARITY=0
THREADS=1

#INPUT=input/input1.%03i
#SOLVED_TEMPLATE=solved/solved1.%02i
#MATCH_TEMPLATE=match/match1.%02i.%02i
#DONE_TEMPLATE=done/done1.%02i.%02i

INPUT=input/input2
SOLVED_TEMPLATE=solved/tmp.solved2
MATCH_TEMPLATE=match/tmp.match2
DONE_TEMPLATE=done/done2

SDEPTH=0
DEPTH=80

QUIET=1

FUL=0.39
FUU=0.41
TOL=0.006

CXDX=0.05
AGREETOL=10
DO_CORRESPOND=0

VERIFY_DIST=4
NAGREE_TOVERIFY=2
OVERLAP_TOSOLVE=0.25
OVERLAP_TOKEEP=0.25
MIN_NINFIELD=50

#FIELD_CHUNKS=35
FIELD_CHUNKS=1

#flds="0/9999"
flds="0/2617"

filenum=-1

# healpixes
#for ((h=0; h<12; h++)); do
for ((h=0; h<1; h++)); do
	cmd="{print \$$(($h+1))}"
	i=`echo $HPORDER | awk "$cmd"` 
	index=`printf $INDEX $i`
	indexsrc=`printf $INDEXSRC $i`
	txt="index $index\n"
	txt="${txt}xcol $XCOL\n"
	txt="${txt}ycol $YCOL\n"
	txt="${txt}sdepth $SDEPTH\ndepth $DEPTH\n"
	if [ x$CXDX != x ]; then
		txt="${txt}cxdx_margin $CXDX\n"
	fi
	txt="${txt}parity $PARITY\ntol $TOL\n"
	if [ x$FUL != x ]; then
		txt="${txt}fieldunits_lower $FUL\n"
	fi
	if [ x$MAXQUADS != x ]; then
		txt="${txt}maxquads $MAXQUADS\n"
	fi
	if [ x$FUU != x ]; then
		txt="${txt}fieldunits_upper $FUU\n"
	fi
	if [ x$SOLVEDSERVER != x ]; then
		txt="${txt}solvedserver $SOLVEDSERVER\n"
	fi
	txt="${txt}agreetol $AGREETOL\n"
	if [ x$VERIFY_DIST != x ]; then
		txt="${txt}verify_dist $VERIFY_DIST\n"
		txt="${txt}nagree_toverify $NAGREE_TOVERIFY\n"
		txt="${txt}overlap_tosolve $OVERLAP_TOSOLVE\n"
		txt="${txt}overlap_tokeep $OVERLAP_TOKEEP\n"
		txt="${txt}min_ninfield $MIN_NINFIELD\n"
	fi
	txt="${txt}do_correspond $DO_CORRESPOND\n"
	if [ x$QUIET == x1 ]; then
		txt="${txt}quiet\n"
	fi
	txt="${txt}threads $THREADS\n"

	# chunks of field files.
	#for ((ff=1; ff<=35;)); do
	for ((ff=1; ff<=1;)); do

		filenum=$((filenum +1))
		filename=`printf $INPUT $filenum`
		echo $filename
		rm -f $filename

		# field files
		#for ((o=1; o<=FIELD_CHUNKS && ff<=35; o++, ff++)); do
		for ((o=1; o<=FIELD_CHUNKS && ff<=1; o++, ff++)); do
			FIELDID=$ff
			FIELD=`printf $FIELD_TEMPLATE $ff`
			match=`printf $MATCH_TEMPLATE $filenum $ff`
			done=`printf $DONE_TEMPLATE $filenum $ff`

			txt2="${txt}field $FIELD\n"
			txt2="${txt2}fieldid $FIELDID\n"
			txt2="${txt2}fields ${flds}\n"
			# (ask the solvedserver for the unsolved field list)
			#txt2="${txt2}firstfield 0\n"
			#txt2="${txt2}lastfield 9999\n"
		    if [ x$SOLVED_TEMPLATE != x ]; then
				SOLVED=`printf $SOLVED_TEMPLATE $ff`
				txt2="${txt2}solved $SOLVED\n"
			fi
			txt2="${txt2}match ${match}\n"
			txt2="${txt2}done ${done}\n"
			txt2="${txt2}run\n"
			echo -n -e $txt2 >> $filename
		done
	done
done

