application: astrometry-render
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/
  static_dir: static

- url: /tileSize
  static_files: static/tileSize.html
  upload: static/tileSize.html

- url: /tileSizeMap.js
  static_files: static/tileSizeMap.js
  upload: static/tileSizeMap.js

- url: /tileSizeB
  static_files: static/tileSizeB.html
  upload: static/tileSizeB.html

- url: /tileSizeMapB.js
  static_files: static/tileSizeMapB.js
  upload: static/tileSizeMapB.js

- url: /tileSizeTile
  script: tilesize.py

- url: /julia
  static_files: static/index.html
  upload: static/index.html

- url: /map.js
  static_files: static/map.js
  upload: static/map.js

- url: /tile.*
  script: julia.py

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: hello.py

