###############################################################################
# astrometry
###############################################################################

SHELL = /bin/sh
#
all :;

install :
	- cp astrometry.table $(ASTROMETRY_DIR)/ups
	- cp Makefile $(ASTROMETRY_DIR)/ups

clean :
	rm -f *~ core *.bak *.orig *.old .#* #*#
