#!/bin/bash
PICASAWEB_USER=$1
echo "export PICASAWEB_USER=\"$PICASAWEB_USER\""
curl --silent \
  "https://www.google.com/accounts/ClientLogin" \
  -d Email=$PICASAWEB_USER@gmail.com -d Passwd=$2 \
  -d accountType=GOOGLE \
  -d source=$0 \
  -d service=lh2 \
  | sed 's/^/export PICASAWEB_/'
