#!/bin/bash
#
# usage:
#   ./picasaweb_create_album album.xml > foo
#   source foo
# comments:
#   DOESN'T WORK!!
#   requires environment variables:
#     PICASAWEB_Auth
#     PICASAWEB_USER
#   you must edit "picasaweb_create_album.xml" by hand to "album.xml"
#   The "source foo" line sets environment variable:
#     PICASAWEB_ALBUMID
#     PICASAWEB_ALBUMNAME
#
curl --silent \
  --request POST \
  --data "@$1" \
  --header "Content-Type: application/atom+xml" \
  --header "Authorization: GoogleLogin auth=$PICASAWEB_Auth" \
  "http://picasaweb.google.com/data/feed/api/user/$PICASAWEB_USER" \
  | sed 's/^.*albumid\//export PICASAWEB_ALBUMID=/' | sed 's/\/.*$/\n/'
