#!/bin/bash
#
# purpose:
#   construct proposed album name from file md5sum hash
# usage:
#   ./picasaweb_albumname filename
# comments:
#   hard-coded to make album names between 001 and 498; ie, magic number 1F2
#   errors result in album name "000"
#
printf "%03d\n" $(echo "ibase=16 ; obase=A ; scale=0 ; 1 + ($(md5sum "$1" | cut -d " " -f 1 | tr a-z A-Z) % 1F2)" | bc)
