#!/bin/bash
#
# usage:
#   ./picasaweb username password > foo
#   source foo
# comments:
#   The "source foo" line sets environment variables:
#     PICASAWEB_USER
#     PICASAWEB_Auth
#
PICASAWEB_USER=$1
echo "export PICASAWEB_USER=\"$PICASAWEB_USER\""
curl --silent \
  "https://www.google.com/accounts/ClientLogin" \
  -d Email=$PICASAWEB_USER@gmail.com -d Passwd=$2 \
  -d accountType=GOOGLE \
  -d source=$0 \
  -d service=lh2 \
  | sed 's/^/export PICASAWEB_/'
