#!/bin/bash
#
# usage:
#   ./picasaweb_upload_image $FILENAME > foo
#   source foo
# comments:
#   requires environment variables:
#     PICASAWEB_Auth
#     PICASAWEB_USER
#     PICASAWEB_ALBUMNAME
#   hard-coded FILETYPE
#   The "source foo" line sets environment variable:
#     PICASAWEB_PHOTOID
#
FILETYPE=jpeg
uri="http://picasaweb.google.com/data/feed/api/user/$PICASAWEB_USER/album/$PICASAWEB_ALBUMNAME"
curl --silent \
  --request POST \
  --data-binary "@$1" \
  --header "Content-Type: image/$FILETYPE" \
  --header "Authorization: GoogleLogin auth=$PICASAWEB_Auth" \
  $uri \
  | sed 's/^.*photoid\//export PICASAWEB_PHOTOID=/' | sed 's/\/.*$/\n/'
