#!/bin/bash
#
# usage:
#   ./picasaweb_create_tag tag
# comments:
#   requires environment variables:
#     PICASAWEB_Auth
#     PICASAWEB_USER
#     PICASAWEB_ALBUMNAME
#     PICASAWEB_PHOTOID
#
FILETYPE=jpeg
uri="http://picasaweb.google.com/data/feed/api/user/$PICASAWEB_USER/album/$PICASAWEB_ALBUMNAME/photo/$PICASAWEB_PHOTOID"
data="<entry xmlns='http://www.w3.org/2005/Atom'><title>$1</title><category scheme=\"http://schemas.google.com/g/2005#kind\" term=\"http://schemas.google.com/photos/2007#tag\"/></entry>"
curl --silent \
  --request POST \
  --data $data \
  --header "Content-Type: application/atom+xml" \
  --header "Authorization: GoogleLogin auth=$PICASAWEB_Auth" \
  $uri
