#!/bin/bash

F=$0-data-orig
FN=$0-data

randcat -f $F -n $NSTARS -S $SEED1 \
        -r $RA_MIN -R $RA_MAX -d $DEC_MIN -D $DEC_MAX &&
startree -f $F &&
genfields -f $F -o $FIELD_NAME -x $ADD -q $REM -w $POSN_NOISE \
          -r $FIELD_RA_CENTER -d $FIELD_DEC_CENTER -s $FIELD_SCALE -S $SEED2 &&
deduplicate -i $F.objs.fits -o $FN.objs.fits -d $DEDUP &&
startree -f $FN &&
#all_quads -f $FN -s $SCALE -l $LOWER -q &&
codetree -f $FN &&
#deduplicate_index -f $FN &&
solvexy -f $FN -o $FIELD_NAME -m $AGREE -t $MATCH -F 100 -H ${FIELD_NAME}.hits \
         -n $MATCHES_NEEDED_TO_AGREE

