#!/bin/sh
tablist -r "scatter_ref__$1.fits" > re
tablist -r "scatter_image$1.fits" > im
tablist -r "scatter_corIM$1.fits" > corrim
tablist -r "scatter_corRE$1.fits" > corrre
tablist -r "scatter_corVE$1.fits" > corrve
#echo "plot 'im','re','corrim' with points 3 4, 'corrre' with points 5 5" | gnuplot -persist
echo "plot 'im','re' with points 5 5,'corrve' with vectors" | gnuplot -persist
