/*
  NAME:
    tweak
  PURPOSE:
    Run WCS tweak on a FITS image (including all extensions)
  INPUTS:
    Run tweak -h to see help
  OPTIONAL INPUTS:
    None yet
  KEYWORD:
  BUGS:
    - Not rigorously tested.
    - Dependencies 
      - needs kdtree-ified usnob or an.net catalog
      - needs xylist generated by fits2xy, or any FITS file with X Y FLUX
  REVISION HISTORY:
  WHO TO SHOOT IF IT BREAKS:
    Keir
*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <math.h>
#include <assert.h>
#include "libwcs/fitsfile.h"
#include "libwcs/wcs.h"
#include "starutil.h"
#include "fitsio.h"
#include "kdtree.h"
#include "kdtree_fits_io.h"
#include "dualtree_rangesearch.h"
#include "healpix.h"
#include "ezfits.h"
#include "sip.h"
#include "sip_util.h"
#include "bl.h"
#include "lm.h"

kdtree_t* cached_kd = NULL;
int cached_kd_hp = 0;

double max(double x, double y)
{
	if (x < y) return y;
	return x;
}
double min(double x, double y)
{
	if (x < y) return x;
	return y;
}


enum opt_flags {
	OPT_CRVAL = 1,
	OPT_CRPIX = 2,
	OPT_CD    = 4,
	OPT_SIP   = 8,
	OPT_SIP_INVERSE   = 16
};

typedef struct tweak_s {
	sip_t* sip;

	// For sources in the image
	int n;
	double *a;
	double *d;
	double *x;
	double *y;

	// Center of field estimate
	double a_bar;  // degrees
	double d_bar;  // degrees
	double radius; // radians (genius!)

	// Cached values of sources in the catalog
	int n_ref;
	double *x_ref;
	double *y_ref;
	double *a_ref;
	double *d_ref;

	// Correspondences
	il* image;
	il* ref;
	dl* dist2;
	il* maybeinliers;
	il* bestinliers;
	il* included;

	int flags;
//	int n;
//	int m;
//	double parameters[500];

	kdtree_t* kd_image;
	kdtree_t* kd_ref;
} tweak_t;

int get_xy(fitsfile* fptr, int hdu, float **x, float **y, int *n)
{
	// Find this extension in fptr (which should be open to the xylist)
	int nhdus, hdutype;
	int status=0;

	if (fits_get_num_hdus(fptr, &nhdus, &status)) {
		fits_report_error(stderr, status);
		exit(-1);
	}

	// Search each HDU looking for the one with SRCEXT==hdu
	int i, ext=-1;
	for (i=1; i<=nhdus; i++) {
		if (fits_movabs_hdu(fptr, i, &hdutype, &status)) {
			fits_report_error(stderr, status);
			exit(-1);
		}
		if (i != 1)
			assert(hdutype != IMAGE_HDU) ;

		if (fits_read_key(fptr, TINT, "SRCEXT ",
					&ext, NULL, &status)) {
			status = 0;
			continue;
		}
		if (ext == hdu)
			break;
	}

	// Sanity
	if (ext != hdu) {
		fprintf(stderr, "Couldn't find xylist for HDU %d\n",hdu);
		exit(-1);
	}
	if (fits_get_hdu_type(fptr, &hdutype, &status)) {
		fits_report_error(stderr, status);
		exit(-1);
	}
	assert(hdutype != IMAGE_HDU);

	// Now pull the X and Y columns
	long l;
	if (fits_get_num_rows(fptr, &l, &status)) {
		fits_report_error(stderr, status);
		exit(-1);
	}
	*n = l;
	fprintf(stderr, "n=%d\n", *n);

	*x = malloc(sizeof(double)* *n);
	*y = malloc(sizeof(double)* *n);
	if (fits_read_col(fptr, TFLOAT, 1, 1, 1, *n, NULL, *x, NULL, &status)) {
		fits_report_error(stderr, status);
		exit(-1);
	}
	if (fits_read_col(fptr, TFLOAT, 2, 1, 1, *n, NULL, *y, NULL, &status)) {
		fits_report_error(stderr, status);
		exit(-1);
	}
	return 0;
}

void get_center_and_radius(double* ra, double* dec, int n,
                          double* ra_mean, double* dec_mean, double* radius)
{
	double* xyz = malloc(3*n*sizeof(double));
	double xyz_mean[3] = {0,0,0};
	int i, j;
	for (i=0; i<n; i++) {
		radec2xyzarr(deg2rad(ra[i]),
		             deg2rad(dec[i]),
		             xyz + 3*i);
	}

	for (i=0; i<n; i++) 
		for (j=0; j<3; j++) 
			xyz_mean[j] += xyz[3*i+j];

	/*
	for (j=0; j<3; j++) 
		xyz_mean[j] /= (double) n;
		*/

	double norm=0;
	for (j=0; j<3; j++) 
		norm += xyz_mean[j]*xyz_mean[j];
	norm = sqrt(norm);

	for (j=0; j<3; j++) 
		xyz_mean[j] /= norm;

	double maxdist2 = 0;
	int maxind = -1;
	for (i=0; i<n; i++) {
		double dist2 = 0;
		for (j=0; j<3; j++) {
			double d = xyz_mean[j]-xyz[3*i+j];
			dist2 += d*d;
		}
		if (maxdist2 < dist2) {
			maxdist2 = dist2;
			maxind = i;
		}
	}
	*radius = sqrt(maxdist2);
	*ra_mean = rad2deg(xy2ra(xyz_mean[0],xyz_mean[1]));
	*dec_mean = rad2deg(z2dec(xyz_mean[2]));
}

void get_reference_stars(double ra_mean, double dec_mean, double radius,
                         double** ra, double **dec, int *n, char* hppat)
{
	// FIXME magical 9 constant == an_cat hp res NSide
	int hp = radectohealpix_nside(deg2rad(ra_mean), deg2rad(dec_mean), 9); 
	kdtree_t* kd;
	if (cached_kd_hp != hp || cached_kd == NULL) {
		char buf[1000];
		snprintf(buf,1000, hppat, hp);
		fprintf(stderr, "opening %s\n",buf);
		kd = kdtree_fits_read_file(buf);
		fprintf(stderr, "success\n");
		assert(kd);
		cached_kd_hp = hp;
		cached_kd = kd;
	} else {
		kd = cached_kd;
	}

	double xyz[3];
	radec2xyzarr(deg2rad(ra_mean), deg2rad(dec_mean), xyz);
	//radec2xyzarr(deg2rad(158.70829), deg2rad(51.919442), xyz);

	// Fudge radius factor because if the shift is really big, then we
	// can't actually find the correct astrometry.
	double radius_factor = 1.3;
	kdtree_qres_t* kq = kdtree_rangesearch(kd, xyz,
			radius*radius*radius_factor);
	fprintf(stderr, "Did range search got %u stars\n", kq->nres);

	*n = kq->nres;

	// No stars? That's bad. Run away.
	if (!*n)
		return;

	*ra = malloc(sizeof(double)*kq->nres);
	*dec = malloc(sizeof(double)*kq->nres);
	assert(*ra);
	assert(*dec);

	int i;
	fprintf(stderr, "ref stars:\n");
	for (i=0; i<kq->nres; i++) {
		double *xyz = kq->results+3*i;
		(*ra)[i] = rad2deg(xy2ra(xyz[0],xyz[1]));
		(*dec)[i] = rad2deg(z2dec(xyz[2]));
		/*
		if (i < 30) {
			fprintf(stderr, "a=%f d=%f\n",(*ra)[i],(*dec)[i]);
			fprintf(stderr, "x=%f y=%f z=%f\n",xyz[0],xyz[1], xyz[2]);
			fprintf(stderr, "dist=%f\n",sqrt(kq->sdists[i]));
			fprintf(stderr, "distdeg=%f\n",sqrt(kq->sdists[i]));
		}
		*/
	}

	kdtree_free_query(kq);
//	kdtree_fits_close(kd);
}

void get_shift(double* ximg, double* yimg, int nimg,
               double* xcat, double* ycat, int ncat, 
               double* xshift, double* yshift)
{

	int i, j;

	// hough transform 
	int hsz = 1000; // hough size
	int *hough = malloc(hsz*hsz*sizeof(double));
	for (i=0; i<hsz*hsz; i++)
		hough[i] = 0;

	double maxdx = -1e100;
	double mindx = 1e100;
	double maxdy = -1e100;
	double mindy = 1e100;
	for (i=0; i<nimg; i++) {
		for (j=0; j<ncat; j++) {
			double dx = ximg[i]-xcat[j];
			double dy = yimg[i]-ycat[j];
			maxdx = max(dx,maxdx);
			maxdy = max(dy,maxdy);
			mindx = min(dx,mindx);
			mindy = min(dy,mindy);
		}
	}


	for (i=0; i<nimg; i++) {
		for (j=0; j<ncat; j++) {
			double dx = ximg[i]-xcat[j];
			double dy = yimg[i]-ycat[j];
			int hszi = hsz-1;
			int iy = hszi*( (dy-mindy)/(maxdy-mindy) );
			int ix = hszi*( (dx-mindx)/(maxdx-mindx) );
			assert (iy >=0);
			assert (ix >=0);
			assert (iy*hsz+ ix < hsz*hsz);
			if (0 < iy && iy < hsz+1 &&
					0 < ix && ix < hsz+1) {
				// approx gauss
				hough[(iy-1)*hsz + (ix-1)] += 1;
				hough[(iy+1)*hsz + (ix+1)] += 1;
				hough[(iy-1)*hsz + (ix+1)] += 1;
				hough[(iy+1)*hsz + (ix-1)] += 1;
				hough[(iy-0)*hsz + (ix-1)] += 4;
				hough[(iy-1)*hsz + (ix-0)] += 4;
				hough[(iy+0)*hsz + (ix+1)] += 4;
				hough[(iy+1)*hsz + (ix+0)] += 4;
				hough[iy*hsz + ix] += 10;
			}
		}
	}

	int themax = 0;
	int themaxind;
	for (i=0; i<hsz*hsz; i++) {
		if (themax < hough[i]) {
			themaxind = i;
			themax = hough[i];
		}
	}

	int ys = themaxind/hsz;
	int xs = themaxind%hsz;

	fprintf(stderr, "xshsz = %d, yshsz=%d\n",xs,ys);

	*yshift = ((double)(themaxind/hsz)/(double)hsz)*(maxdy-mindy)+mindy;
	*xshift = ((double)(themaxind % hsz)/(double)hsz)*(maxdx-mindx)+mindx;
	fprintf(stderr, "xs=%lf, ys=%lf\n", *xshift, *yshift);

	static char c = '1';
	static char fn[] = "houghN.fits";
	fn[5] = c++;
//	ezwriteimage(fn, TINT, hough, hsz, hsz);
}

// Take shift in image plane and do a switcharoo to make the wcs something
// better
sip_t* wcs_shift(sip_t* wcs, double xs, double ys)
{
	sip_t* swcs = malloc(sizeof(sip_t));
	memcpy(swcs, wcs, sizeof(sip_t));

	// Save
	double crpix0 = wcs->crpix[0];
	double crpix1 = wcs->crpix[1];

	wcs->crpix[0] += xs;
	wcs->crpix[1] += ys;

	// now reproject the old crpix[xy] into swcs
	double nxref, nyref;
	pixelxy2radec(wcs, crpix0, crpix1, &nxref, &nyref);

	swcs->crval[0] = nxref;
	swcs->crval[1] = nyref;

	// Restore
	wcs->crpix[0] = crpix0;
	wcs->crpix[1] = crpix1;

	return swcs;
}
// Grabs the data we need for tweak from various sources:
// XY locations in pixel space
// AD locations corresponding to sources
// estimated field center / radius
// XY reference locations
// AD reference locations
int get_tweak_data(tweak_t* t, fitsfile* xyfptr, char* hppat, int hdu)
{
	// Extract XY from FITS table as floats
	int jj;
	float *xf, *yf;
	get_xy(xyfptr, hdu, &xf, &yf, &t->n);

	// Convert to doubles FIXME cfitsio may be able to do this
	t->x = malloc(sizeof(double)*t->n);
	t->y = malloc(sizeof(double)*t->n);
	for (jj=0; jj<t->n; jj++) {
		t->x[jj] = xf[jj];
		t->y[jj] = yf[jj];
	}

	// Convert to ra dec
	t->a = malloc(sizeof(double)*t->n);
	t->d = malloc(sizeof(double)*t->n);
	for (jj=0; jj<t->n; jj++) {
		pixelxy2radec(t->sip, t->x[jj], t->y[jj], t->a+jj, t->d+jj);
//		if (jj < 30) 
//			printf("::: %lf %lf\n", t->a[jj], t->d[jj]);
	}

//	ezscatter("scatter_image.fits", t->x,t->y,t->a,t->d,t->n);

	// Find field center/radius
	get_center_and_radius(t->a, t->d, t->n,
	                      &t->a_bar, &t->d_bar, &t->radius);
	fprintf(stderr, "abar=%f, dbar=%f, radius in rad=%f\n",
	                 t->a_bar, t->d_bar, t->radius);

	// Get the reference stars from our catalog
	get_reference_stars(t->a_bar, t->d_bar, t->radius,
			    &t->a_ref, &t->d_ref, &t->n_ref, hppat);
	if (!t->n_ref)  {
		// No reference stars? This is bad.
		fprintf(stderr, "No reference stars; failing\n");
		free(t->a);
		free(t->d);
		free(t->x);
		free(t->y);
		return 0;
	}

	// Shift runs in XY; project reference stars
	t->x_ref = malloc(sizeof(double)*t->n_ref);
	t->y_ref = malloc(sizeof(double)*t->n_ref);
	for (jj=0; jj<t->n_ref; jj++) {
		radec2pixelxy(t->sip, t->a_ref[jj], t->d_ref[jj],
		              t->x_ref+jj, t->y_ref+jj);
	}
	return 1;
}

sip_t* do_entire_shift_operation(tweak_t* t)
{
//	ezscatter("scatter_usno.fits", x_ref,y_ref,a_ref,d_ref,n_ref);

	printf("----- entire shift\n");
	// Run our wonderful shift algorithm
	double xshift, yshift;
	get_shift(t->x, t->y, t->n,              // Image
	          t->x_ref, t->y_ref, t->n_ref,  // Reference
	          &xshift, &yshift);
	sip_t* swcs = wcs_shift(t->sip, xshift, yshift);
	free(t->sip);
	t->sip = swcs;
	printf("xshift=%lf, yshift=%lf\n", xshift, yshift);
	return NULL;
}

typedef struct { il* image; il* ref; dl* dist2; } dualtree_data_t;

// Dualtree rangesearch callback. We want to keep track of correspondences.
// If we get called multiple times with the same image_ind, then we take the
// ref_ind which is closest.
void match_callback(void* extra, int image_ind, int ref_ind, double dist2)
{
	tweak_t* t = extra;

	image_ind = t->kd_image->perm[image_ind];
	ref_ind = t->kd_ref->perm[ref_ind];


	double dx = t->x[image_ind] - t->x_ref[ref_ind];
	double dy = t->y[image_ind] - t->y_ref[ref_ind];

	printf("found new one!: dx=%lf, dy=%lf, dist=%lf\n",
			dx,dy,sqrt(dx*dx+dy*dy));
	il_append(t->image, image_ind);
	il_append(t->ref, ref_ind);
	dl_append(t->dist2, dist2);
	il_append(t->included, 1);
}

void find_correspondences(tweak_t* t)
{
	double* data_image = malloc(sizeof(double)*t->n*2);
	double* data_ref = malloc(sizeof(double)*t->n_ref*2);

	int i;
	for (i=0; i<t->n; i++) {
		data_image[2*i+0] = t->x[i];
		data_image[2*i+1] = t->y[i];
	}

	int levels = kdtree_compute_levels(t->n, 4);
	t->kd_image = kdtree_build(data_image, t->n, 2, levels);

	for (i=0; i<t->n_ref; i++) {
		data_ref[2*i+0] = t->x_ref[i];
		data_ref[2*i+1] = t->y_ref[i];
	}
	levels = kdtree_compute_levels(t->n_ref, 4);
	t->kd_ref = kdtree_build(data_ref, t->n_ref, 2, levels);

	// Storage for correspondences
	t->image = il_new(600);
	t->ref = il_new(600);
	t->dist2 = dl_new(600);
	t->included = il_new(600);

	// Find closest neighbours
	dualtree_rangesearch(t->kd_image, t->kd_ref,
	                     RANGESEARCH_NO_LIMIT, 15, // This min/max dist is in pixels
	                     match_callback, t,
	                     NULL, NULL);

	printf("im=%d\n", il_size(t->image)); 
	printf("ref=%d\n", il_size(t->ref)); 
	printf("dist2=%d\n", il_size(t->dist2)); 
	dl_print(t->dist2);
}

void free_extraneous(tweak_t* t) 
{
	// don't free x and y because we don't compute them
	if (t->a) free(t->a);
	if (t->d) free(t->d);
	if (t->a_ref) free(t->a_ref);
	if (t->d_ref) free(t->d_ref);
	if (t->x_ref) free(t->x_ref);
	if (t->y_ref) free(t->y_ref);
}


void dump_data(tweak_t* t)
{
	static char s = '1';
	char fn[] = "scatter_imageN.fits";
	fn[13] = s;
	ezscatter(fn, t->x,t->y,t->a,t->d,t->n);

	char fn2[] = "scatter_ref__N.fits";
	fn2[13] = s;
	ezscatter(fn2, t->x_ref,t->y_ref,t->a_ref,t->d_ref,t->n_ref);

	if (t->image) {
		double *a, *d, *x, *y;
		a = malloc(sizeof(double)*il_size(t->image));
		d = malloc(sizeof(double)*il_size(t->image));
		x = malloc(sizeof(double)*il_size(t->image));
		y = malloc(sizeof(double)*il_size(t->image));
		double *a_ref, *d_ref, *x_ref, *y_ref;
		a_ref = malloc(sizeof(double)*il_size(t->image));
		d_ref = malloc(sizeof(double)*il_size(t->image));
		x_ref = malloc(sizeof(double)*il_size(t->image));
		y_ref = malloc(sizeof(double)*il_size(t->image));

		double *dx, *dy;
		dx = malloc(sizeof(double)*il_size(t->image));
		dy = malloc(sizeof(double)*il_size(t->image));
		
		int i;
		for (i=0; i<il_size(t->image); i++) {
			int im_ind = il_get(t->image, i);
			x[i] = t->x[im_ind];
			y[i] = t->y[im_ind];
			pixelxy2radec(t->sip, x[i],y[i], a+i,d+i);
//			a[i] = t->a[im_ind];
//			d[i] = t->d[im_ind];

			int ref_ind = il_get(t->ref, i);
			a_ref[i] = t->a_ref[ref_ind];
			d_ref[i] = t->d_ref[ref_ind];
			// Must recompute ref xy's
//			radec2pixelxy(t->sip, a_ref[i], d_ref[i], 
//					x_ref +i, y_ref+i);
			x_ref[i] = t->x_ref[ref_ind];
			y_ref[i] = t->y_ref[ref_ind];

			dx[i] = x_ref[i] - x[i];
			dy[i] = y_ref[i] - y[i];
		}
		char fn3[] = "scatter_corIMN.fits";
		char fn4[] = "scatter_corREN.fits";
		char fn5[] = "scatter_corVEN.fits";
		fn3[13] = s;
		fn4[13] = s;
		fn5[13] = s;
		ezscatter(fn3, x,y,a,d,il_size(t->image));
		ezscatter(fn4, x_ref,y_ref,a_ref,d_ref,il_size(t->image));
		ezscatter(fn5, x, y, dx, dy, il_size(t->image));
		free(a);
		free(d);
		free(x);
		free(y);
		free(a_ref);
		free(d_ref);
		free(x_ref);
		free(y_ref);
	}
	s++;
}

// Our parameter vector is 'p' for LM. The breakdown of parameters into the
// parameter vector goes in the following order:
//
// OPT_CRVAL       CRVAL0
//                 CRVAL1
//               
// OPT_CRPIX       CRPIX0
//                 CRPIX1
//               
// OPT_CD          CD1_1
//                 CD1_2
//                 CD2_1
//                 CD2_2
//                 
// OPT_SIP         A_1_2         Note that A_1_1 is not present; it is 0
//                 A_1_3
//                 A_1_4
//                 A_1_5
//                 A_1_a_order   All A matrix terms listed in row-major order;
//                               same for B matrix. All terms are such that
//                               i+j <= a_order. Below-cross-diagonal terms
//                               are implicitly zero.
//                 B_1_1
//                 B_1_2         ... and so on

void unpack_params(sip_t* sip, double *pp, int flags) 
{
	assert(pp);
	assert(sip);
	if (flags & OPT_CRVAL) {
		sip->crval[0] = *pp++;
		sip->crval[1] = *pp++;
	}
	if (flags & OPT_CRPIX) {
		sip->crpix[0] = *pp++;
		sip->crpix[1] = *pp++;
	}
	if (flags & OPT_CD) {
		sip->cd[0][0] = *pp++;
		sip->cd[0][1] = *pp++;
		sip->cd[1][0] = *pp++;
		sip->cd[1][1] = *pp++;
	}
	if (flags & OPT_SIP) {
		int p, q;
		for (p=0; p<sip->a_order; p++)
			for (q=0; q<sip->a_order; q++)
				if (p+q <= sip->a_order && !(p==0&&q==0))
					 sip->a[p][q] = *pp++;
		for (p=0; p<sip->b_order; p++)
			for (q=0; q<sip->b_order; q++)
				if (p+q <= sip->b_order && !(p==0&&q==0))
					 sip->b[p][q] = *pp++;
	}
	if (flags & OPT_SIP_INVERSE) {
		int p, q;
		for (p=0; p<sip->ap_order; p++)
			for (q=0; q<sip->ap_order; q++)
				if (p+q <= sip->ap_order && !(p==0&&q==0))
					 sip->ap[p][q] = *pp++;
		for (p=0; p<sip->bp_order; p++)
			for (q=0; q<sip->bp_order; q++)
				if (p+q <= sip->bp_order && !(p==0&&q==0))
					 sip->bp[p][q] = *pp++;
	}
}

int pack_params(sip_t* sip, double *parameters, int flags) 
{
	double* pp = parameters;
	if (flags & OPT_CRVAL) {
		*pp++ = sip->crval[0];
		*pp++ = sip->crval[1];
	}
	if (flags & OPT_CRPIX) {
		*pp++ = sip->crpix[0];
		*pp++ = sip->crpix[1];
	}
	if (flags & OPT_CD) {
		*pp++ = sip->cd[0][0];
		*pp++ = sip->cd[0][1];
		*pp++ = sip->cd[1][0];
		*pp++ = sip->cd[1][1];
	}
	if (flags & OPT_SIP) {
		printf("Packing SIP||||||||\n");
		int p, q;
		for (p=0; p<sip->a_order; p++)
			for (q=0; q<sip->a_order; q++)
				if (p+q <= sip->a_order && !(p==0&&q==0)) {
					if (sip->a[p][q] != 0.00) 
						printf("Found nonzero=%le\n", sip->a[p][q]);
					  *pp++ = sip->a[p][q];
				}
		for (p=0; p<sip->b_order; p++)
			for (q=0; q<sip->b_order; q++)
				if (p+q <= sip->b_order && !(p==0&&q==0))
					  *pp++ = sip->b[p][q];
	}

	if (flags & OPT_SIP_INVERSE) {
		int p, q;
		for (p=0; p<sip->ap_order; p++)
			for (q=0; q<sip->ap_order; q++)
				if (p+q <= sip->ap_order && !(p==0&&q==0))
					  *pp++ = sip->ap[p][q];
		for (p=0; p<sip->bp_order; p++)
			for (q=0; q<sip->bp_order; q++)
				if (p+q <= sip->bp_order && !(p==0&&q==0))
					  *pp++ = sip->bp[p][q];
	}
	return pp - parameters;
}

// RIFE with optimization opportunities
void cost(double *p, double *hx, int m, int n, void *adata)
{
	tweak_t* t = adata;

	sip_t sip;
	memcpy(&sip, t->sip, sizeof(sip_t));
	unpack_params(&sip, p, t->flags);

	// Run the gauntlet.
	double err = 0; // calculate our own sum-squared error
	int i;
	for (i=0; i<il_size(t->image); i++) {
//		if (!il_get(t->included, i)) 
//			continue;
		double a, d;
		int image_ind = il_get(t->image, i);
		pixelxy2radec(&sip, t->x[image_ind], t->y[image_ind], &a, &d);
		double image_xyz[3];
		radecdeg2xyzarr(a, d, image_xyz);
		*hx++ = image_xyz[0];
		*hx++ = image_xyz[1];
		*hx++ = image_xyz[2];

		double ref_xyz[3];
		int ref_ind = il_get(t->ref, i);
		radecdeg2xyzarr(t->a_ref[ref_ind], t->d_ref[ref_ind], ref_xyz);
		double dx = ref_xyz[0] - image_xyz[0];
		double dy = ref_xyz[1] - image_xyz[1];
		double dz = ref_xyz[2] - image_xyz[2];
		err += dx*dx+dy*dy+dz*dz;
//		printf("dx=%le, dy=%le, dz=%le\n",dx,dy,dz);

	}
	printf("sqd error=%le\n", err);
}

// Do a fit.
// Requires: correspondences     t->image, t->ref,
//           image sources       t->x,t->y,
//           reference sources   t->a_ref,t->d_ref
//           optimization flags  t->flags
//           initial SIP guess   t->sip
void lm_fit(tweak_t* t)
{
	double params[410];
//	t->flags = OPT_CRVAL | OPT_CRPIX | OPT_CD;
//	t->flags = OPT_CRVAL | OPT_CD;
	t->flags = OPT_CRVAL | OPT_CRPIX | OPT_CD | OPT_SIP;
	t->sip->a_order = 3;
	t->sip->b_order = 3;

	printf("BEFORE::::::::::\n");
	print_sip(t->sip);

	//WTF
//	t->sip->cd[0][0] *= 1.41;
//	t->sip->cd[0][1] *= 1.41;
//	t->sip->cd[1][0] *= 1.41;
//	t->sip->cd[1][1] *= 1.41;

//	t->sip->crval[0] *= 1.61;
//	t->sip->crval[1] *= 1.22;

//	t->sip->crpix[0] *= 5.01;
//	t->sip->crpix[1] *= 1.02;
//	t->sip->a[2][2] = 5555;
//	t->sip->b[2][2] = -1111;
//	t->sip->a[1][1] = 44.44;
//	t->sip->b[1][1] = -2.22;


	print_sip(t->sip);

	int m =  pack_params(t->sip, params, t->flags);
	printf("REPACKED::::::::::\n");
	sip_t sip;
	memcpy(&sip, t->sip, sizeof(sip_t));
	unpack_params(&sip, params, t->flags);
	print_sip(&sip);

	// Pack target values
	double *desired = malloc(sizeof(double)*il_size(t->image)*3);
	double *hx = desired;
	int i;
	for (i=0; i<il_size(t->image); i++) {
//		if (!il_get(t->included, i)) 
//			continue;
		int ref_ind = il_get(t->ref, i);
		double ref_xyz[3];
		radecdeg2xyzarr(t->a_ref[ref_ind], t->d_ref[ref_ind], ref_xyz);
		*hx++ = ref_xyz[0];
		*hx++ = ref_xyz[1];
		*hx++ = ref_xyz[2];
	}

	int n = t->n = hx - desired;
	assert(hx-desired == 3*il_size(t->image));

	printf("Starting optimization m=%d n=%d!!!!!!!!!!!\n",m,n);
	double info[LM_INFO_SZ];
	int max_iterations = 200;
	double opts[] = { 0.0000000001*LM_INIT_MU,
	                  0.0000000001*LM_STOP_THRESH,
	                  0.0000000001*LM_STOP_THRESH,
		          0.0000000001*LM_STOP_THRESH,
	                  0.0000000001*-LM_DIFF_DELTA};
	dlevmar_dif(cost, params, desired, m, n, max_iterations,
	            opts, info, NULL, NULL, t);

	printf("initial error^2 = %le\n", info[0]);
	printf("final   error^2 = %le\n", info[1]);
	printf("nr iterations   = %lf\n", info[5]);
	printf("term reason     = %lf\n", info[6]);
	printf("function evals  = %lf\n", info[7]);

	unpack_params(t->sip, params, t->flags);
//	memcpy(t->parameters, params, sizeof(double)*t->n);
}


// RANSAC from Wikipedia:
// Given:
//     data - a set of observed data points
//     model - a model that can be fitted to data points
//     n - the minimum number of data values required to fit the model
//     k - the maximum number of iterations allowed in the algorithm
//     t - a threshold value for determining when a data point fits a model
//     d - the number of close data values required to assert that a model fits well to data
// Return:
//     bestfit - model parameters which best fit the data (or nil if no good model is found)
// iterations = 0
// bestfit = nil
// besterr = something really large
// while iterations < k {
//     maybeinliers = n randomly selected values from data
//     maybemodel = model parameters fitted to maybeinliers
//     alsoinliers = empty set
//     for every point in data not in maybeinliers {
//         if point fits maybemodel with an error smaller than t
//              add point to alsoinliers
//     }
//     if the number of elements in alsoinliers is > d {
//         % this implies that we may have found a good model
//         % now test how good it is
//         bettermodel = model parameters fitted to all points in maybeinliers and alsoinliers
//         thiserr = a measure of how well model fits these points
//         if thiserr < besterr {
//             bestfit = bettermodel
//             besterr = thiserr
//         }
//     }
//     increment iterations
// }
// return bestfit

/*
void ransac(tweak_t* t)
{
	int iterations = 0;
	int maxiter = 1000;

	double *bestfit = malloc(sizeof(double)*t->m);
	double *maybemodel = malloc(sizeof(double)*t->m);
	memcpy(bestparameters, t->parameters, sizeof(double)*t->m);
	memcpy(maybeparameters, t->parameters, sizeof(double)*t->m);

	t->maybeinliers = il_new(600);
	t->bestinliers = il_new(600);

	double besterr = 100000000000000;
	int min_data_points = 30;
	int *maybeinliers = malloc(sizeof(int)*min_data_points);
	int setsize = il_size(t->image);
	while (iterations < maxiter) {
		// select n random integers... with replacement because i'm
		// really lazy
		for (i=0; i<min_data_points; i++) {
			maybeinliers[i] = rand()/(double)RAND_MAX * set_size;
			printf("eeeeeeeeeeeeeeeee %d\n", maybeinliers[i]);
		}
	}
}
*/


void printHelp(char* progname)
{
	fprintf(stderr, "%s usage:\n"
	        "   -i <input file>      file to tweak\n"
	        "   -o <output-file>     destination file\n"
	        "   -s <xy-list>         sources (produced by fits2xy)\n"
	        "   -d <database-subst>  pattern for the index\n"
	        "   -n <healpix-nside>   number of healpixes in index\n"
	        , progname);
}

extern char *optarg;
extern int optind, opterr, optopt;

int main(int argc, char *argv[])
{
	//sip_t* wcs;
	fitsfile *fptr, *xyfptr;  /* FITS file pointer, defined in fitsio.h */
	//fitsfile *ofptr;        /* FITS file pointer to output file */
	int status = 0; // FIXME should have ostatus too
	int naxis;
	int kk;
	char* xyfile = NULL;
	char* outfile = NULL;
	char* infile = NULL;
	char* hppat = NULL;
	int Nside = 0;
	char argchar;

	while ((argchar = getopt(argc, argv, "hi:s:o:d:n:")) != -1)
		switch (argchar) {
		case 'h':
			printHelp(argv[0]);
			exit(0);
		case 'i':
			infile = optarg;
			break;
		case 's':
			xyfile = optarg;
			break;
		case 'o':
			outfile = optarg;
			break;
		case 'd':
			hppat = optarg;
			break;
		case 'n':
			Nside = atoi(optarg);
			break;
		}

	if (!outfile || !infile || !xyfile || !hppat || !Nside) {
		printHelp(argv[0]);
		exit( -1);
	}

	if (fits_open_file(&fptr, infile, READONLY, &status)) {
		fprintf(stderr, "Error reading image file %s\n", infile);
		fits_report_error(stderr, status);
		exit(-1);
	}

	int nhdus;
	if (fits_get_num_hdus(fptr, &nhdus, &status)) {
		fits_report_error(stderr, status);
		exit(-1);
	}
	fprintf(stderr, "nhdus=%d\n", nhdus);

	// Load xylist
	if (fits_open_file(&xyfptr, xyfile, READONLY, &status)) {
		fprintf(stderr, "Error reading XY file %s\n", xyfile);
		fits_report_error(stderr, status);
		exit(-1);
	}

	// Tweak each HDU independently
	for (kk=1; kk <= nhdus; kk++) {
		int hdutype;
		if (fits_movabs_hdu(fptr, kk, &hdutype, &status)) {
			fits_report_error(stderr, status);
			exit(-1);
		}

		if (fits_get_hdu_type(fptr, &hdutype, &status)) {
			fits_report_error(stderr, status);
			exit(-1);
		}

		if (hdutype != IMAGE_HDU) 
			continue;

		if (fits_get_img_dim(fptr, &naxis, &status)) {
			fits_report_error(stderr, status);
			exit( -1);
		}

		if (naxis != 2) {
			fprintf(stderr, "Invalid image: NAXIS is not 2 in HDU %d!\n", kk);
			continue;
		}

		// FIXME BREAK HERE into new function
		tweak_t tweak;

		// At this point, we have an image. Now get the WCS data
		tweak.sip = load_sip_from_fitsio(fptr);
		if (!tweak.sip) {
			fprintf(stderr, "Problems with WCS info, skipping HDU\n");
			continue;
		}
		print_sip(tweak.sip);


		get_tweak_data(&tweak, xyfptr, hppat, kk);
		do_entire_shift_operation(&tweak);
		free_extraneous(&tweak);

		get_tweak_data(&tweak, xyfptr, hppat, kk);
		do_entire_shift_operation(&tweak);
		free_extraneous(&tweak);

//		get_tweak_data(&tweak, xyfptr, hppat, kk);
//		do_entire_shift_operation(&tweak);
//		free_extraneous(&tweak);

		get_tweak_data(&tweak, xyfptr, hppat, kk);
		do_entire_shift_operation(&tweak);
		free_extraneous(&tweak);
		get_tweak_data(&tweak, xyfptr, hppat, kk);

		find_correspondences(&tweak);

		dump_data(&tweak);

		lm_fit(&tweak);
		print_sip(tweak.sip);
//		free_extraneous(&tweak);
//		get_tweak_data(&tweak, xyfptr, hppat, kk);

		dump_data(&tweak);

		if (cached_kd)
			kdtree_fits_close(cached_kd);
		exit(1);
	}


	if (status == END_OF_FILE)
		status = 0; /* Reset after normal error */

	fits_close_file(fptr, &status);

	if (status)
		fits_report_error(stderr, status); /* print any error message */
	return (status);
	

	/* Fink-Hogg shift */
	/* Fink-Hogg shift */
	/* Correspondeces via spherematch -- switch to dualtree */
	/* Linear tweak */
	/* Non-linear tweak */

}
