#!/bin/bash
#
# usage:
#   ./apod_calibrate low high depth
# purpose:
#   calibrate astrometrically ALL of APOD
# comments:
#   low,high in degrees width
#   you must have previously run apod_rearrange from this same cwd
#   brittle
#
date --iso=seconds
topdir=$(pwd)
for days in $(seq 0 5000); do
  dir=$(\date --date "now - $days day" +%Y/%m/%d)
  if [ -d "$dir" ]; then
    \cd "$dir"
    pwd
    for filename in $(ls *.jpg *.png *.gif *.tif); do
      echo "working on $filename"
      prefix=$(expr $filename : '\(.*\)\.[A-z]*')
      if [ -e "$prefix.solved" ]; then
	echo "previously solved $filename, I think"
      else
        solve-field \
          --scale-units "degwidth" \
	  --scale-low "$1" \
          --scale-high "$2" \
	  --depth "0-$3" \
	  --no-plots \
	  --no-fits2fits \
	  --overwrite \
	  "$filename"
      fi
    done
  fi
\cd "$topdir"
date --iso=seconds
done
