#!/bin/bash
#
# usage:
#   ./apod_stuff_image 2008-01-17
# purpose:
#   read one APOD image and stuff it and meta-data into Picasaweb
# comments:
#   requires environment variables
#     APOD_ROOT
#     PICASAWEB_ALBUMID
#     [ other PICASAWEB variables ]
#   depends on picasaweb bash tools (in src/picasaweb)
#   assumes that there is an album named by the year
#   stuffs preview image not "_big" image
#   very brittle
#   this would be better written in Python with a python HTML
#     library (that, eg, reads HTML into Python structures)
#
year=$(echo $1 | sed 's/^\([0-9][0-9][0-9][0-9]\)-..-..$/\1/')
shortyear=$(echo $1 | sed 's/^..\([0-9][0-9]\)-..-..$/\1/')
month=$(echo $1 | sed 's/^....-\([0-9][0-9]\)-..$/\1/')
day=$(echo $1 | sed 's/^....-..-\([0-9][0-9]\)$/\1/')
echo "$year $shortyear $month $day"
htmlname="$APOD_ROOT/ap$shortyear$month$day.html"
caption=$(sed -n 's/<[Tt][Ii][Tt][Ll][Ee]>\(.*\)/\1/p' $htmlname | sed 's/<.*>//')
echo $caption
imgfile=$(sed -n 's/^.*<[Ii][Mm][Gg].*[Ss][Rr][Cc]=\"\(.*\)\".*$/\1/p' $htmlname)
echo $imgfile
../picasaweb/picasaweb_upload_image $FILENAME > ./foo
source ./foo
