#!/bin/bash
#
# usage:
#   ./apod_calibrate low high depth
# purpose:
#   calibrate astrometrically ALL of APOD
# comments:
#   low,high in degrees width
#   you must have previously run apod_rearrange from this same cwd
#   brittle
#
date --iso=seconds
topdir=$(pwd)
for days in $(seq 0 5000); do
    dir=$(\date --date "now - $days day" +%Y/%m/%d)
    if [ -d "$dir" ]; then
	\cd "$dir"
	pwd
	filename=$(ls *.jpg *.png *.gif *.tif | head -1)
	prefix=$(expr $filename : '\(.*\)\.[A-z]*')
	if [ -e "$prefix.solved" ]; then
	    echo "I have already calibrated $filename, I think"
	else
	    xylsname="$prefix.xyls"
	    if [ -e "$xylsname" ]; then
		filename="$xylsname"
		xylsoption=""
	    else
		xylsoption="--keep-xylist $xylsname"
	    fi
	    echo "working on $filename"
	    solve-field \
		--scale-units "degwidth" \
		--scale-low "$1" \
		--scale-high "$2" \
		--depth "$3" \
		--no-plots \
		--no-fits2fits \
		--overwrite \
		$xylsoption \
		"$filename"
	fi
    fi
    \cd "$topdir"
    date --iso=seconds
done
