#!/bin/bash
#
# usage:
#   ./apod_wget
# purpose:
#   download the entire APOD tree with all images
#
wget \
  --recursive \
  --convert-links \
  --page-requisites \
  --no-parent \
  -L \
  "http://apod.nasa.gov/apod/archivepix.html"
