#!/bin/bash
#
# usage:
#   ./apod_rearrange_one iso-formatted-date
# purpose:
#   move the apod data for one day into a sensible directory structure
# comments:
#   requires environment variables
#     APOD_ROOT
#   moves only the "preview" or "inline" image, not the "big" image
#   very brittle
#
year=$(echo $1 | sed 's/^\([0-9][0-9][0-9][0-9]\)-..-..$/\1/')
shortyear=$(echo $1 | sed 's/^..\([0-9][0-9]\)-..-..$/\1/')
month=$(echo $1 | sed 's/^....-\([0-9][0-9]\)-..$/\1/')
day=$(echo $1 | sed 's/^....-..-\([0-9][0-9]\)$/\1/')
htmlname="$APOD_ROOT/ap$shortyear$month$day.html"
if [ -e "$htmlname" ]; then
  directory="$year/$month/$day" 
  \mkdir -p "$directory"
  imgfile=$(sed -n 's/^.*<[Ii][Mm][Gg][^>]*[Ss][Rr][Cc]=\"\([^\"]*\)\".*$/\1/p' $htmlname | head -1)
  imgfile="$APOD_ROOT/$imgfile"
  \cp -fv "$htmlname" "$imgfile" "$directory"
fi

