#!/bin/bash

VALGRIND="valgrind --tool=memcheck --leak-check=full --show-reachable=yes --num-callers=30 --leak-resolution=high"

F=testme_cat_orig

#Nstars=1000
Nstars=4

SEED1=500

CMD="randcat -f $F -n $Nstars -r 0.1745 -R 0.1920 -d 0.1745 -D 0.1920 -S $SEED1"
echo $CMD
$CMD

CMD="startree -f $F"
echo $CMD
$CMD

O=testme_field

#ADD=0.1
#REM=0.1
#POSN_NOISE=0.01

ADD=0
REM=0
POSN_NOISE=0
#FIELDSIZE=30
FIELDSIZE=1000

SEED2=514

CMD="genfields -f $F -o $O -x $ADD -q $REM -w $POSN_NOISE -r 10.5 -d 10.5 -s $FIELDSIZE -S $SEED2"
echo $CMD
$CMD

printheaders -f $F -m > catalog.m
xylstomatlab testme_field.rdls fieldradec 2> field.m

FN=testme_cat

DEDUP=10

CMD="deduplicate -i $F.objs -o $FN.objs -d $DEDUP"
echo $CMD
$CMD

CMD="startree -f $FN"
echo $CMD
$CMD

#SCALE=10
#LOWER=0.25
SCALE=1000
LOWER=0

CMD="all_quads -f $FN -s $SCALE -l $LOWER -q"
echo $CMD
$CMD

CMD="codetree2 -f $FN"
echo $CMD
$CMD

# agreement tolerance: arcseconds
AGREE=100
# code match tolerance: 6-d distance
MATCH=0.001

CMD="solvexy2 -f $FN -o $O -m $AGREE -t $MATCH -F 100 -H ${O}.hits"
echo $CMD
$CMD

