#!/bin/bash

F=testme_cat_orig
FN=testme_cat
FIELD_NAME=testme_field
NSTARS=4

# Parameters to genfields
ADD=0
REM=0
POSN_NOISE=0

# Parameters for randcat catalog creation
RA_MIN=0.1745
RA_MAX=0.1920 
DEC_MIN=0.1745
DEC_MAX=0.1920

# Genfield center and number of stars
FIELD_RA_CENTER=10.5
FIELD_DEC_CENTER=10.5
FIELD_SCALE=100

# Random seed for randcat
SEED1=501
# Random seed for genfields
SEED2=514

# Dedup threshold in arcsecs
DEDUP=10

# Scale range for quads
LOWER=0
SCALE=1000

# Agreement tolerance: arcseconds
AGREE=100  
# Code match tolerance: 6-d distance
MATCH=0.001
# How many quads must agree to get a valid match
MATCHES_NEEDED_TO_AGREE=1

. run_test
