CFITS_DIR := $(BASEDIR)/cfitsio
CFITS_INC := -I$(CFITS_DIR)
CFITS_LIB := $(CFITS_DIR)/libcfitsio.a
CFITS_CFLAGS := $(CFLAGS_DEF)


$(CFITS_LIB): $(wildcard $(CFITS_DIR)/*.c) $(wildcard $(CFITS_DIR)/*.h) $(CFITS_DIR)/Makefile
	$(MAKE) -C cfitsio

$(CFITS_DIR)/Makefile: $(CFITS_DIR)/Makefile.in
	cd $(CFITS_DIR) && ./configure
