CFITS_DIR := $(BASEDIR)/cfitsio
CFITS_INC := -I$(CFITS_DIR)
CFITS_LIB := $(CFITS_DIR)/libcfitsio.a
CFITS_CFLAGS := $(CFLAGS_DEF)


#$(CFITSIO_LIB): $(wildcard cfitsio/*.c) $(wildcard cfitsio/*.h) cfitsio/Makefile
#	$(MAKE) -C cfitsio

#cfitsio/Makefile: cfitsio/Makefile.in
#	cd cfitsio && ./configure
