# Dependencies:           
DEPS := $(subst .o,.dep,$(DEP_OBJ))

deps: $(DEP_PREREQS) $(DEPS)
	cat $(DEPS) > deps

%.dep : %.c
	$(CC) -MM $(CFLAGS) -c $< > $@

ifeq ($(MAKECMDGOALS),clean)
else ifeq ($(MAKECMDGOALS),realclean)
else ifeq ($(MAKECMDGOALS),allclean)
  include deps
endif
