ANUTILS_DIR := $(BASEDIR)/an-common
ANUTILS_INC := -I$(ANUTILS_DIR)
ANUTILS_LIB := $(ANUTILS_DIR)/libanutils.a

#ANUTILS_OBJS := $(addprefix $(ANUTILS_DIR)/, fitsioutils.o)

$(ANUTILS_LIB):
	cd $(ANUTILS_DIR) && make
