#! /bin/bash

LEN=`ls -s --block-size=1 $1 | gawk '{print $1}'`
if [ "x$LEN" == "x" ]; then
  exit
fi
echo "File length $LEN"
if [ $(($LEN % 2880)) -eq 0 ]; then
  exit
else
  PAD=$((2880 - $LEN % 2880))
  echo "Adding $PAD bytes"
  dd bs=1 if=/dev/zero of=a.0 seek=$LEN count=$PAD
fi

