#! /bin/bash

INDEX="$1"
INFILE="$2"

sumstars=0
sumquads=0

declare -a nquads
declare -a nstars

for ((j=0; j<12; j++)); do
  ind=`printf $INDEX%02i $j`

  cmd="modhead $ind.quad.fits NQUADS"
  #echo "$cmd"
  nquads[$j]=$($cmd | gawk '{print $3}')
  #echo "==> ${nquads[j]} quads"

  cmd="modhead $ind.quad.fits NSTARS"
  #echo "$cmd"
  nstars[$j]=$($cmd | gawk '{print $3}')
  #echo "==> ${nstars[j]} stars"

  sumstars=$(($sumstars + ${nstars[j]}))
  sumquads=$(($sumquads + ${nquads[j]}))
done

INDEX_ID=$(modhead "${ind}.quad.fits" INDEXID | gawk '{print $3}')
INDEX_NAME=$INDEX
SCALE_U=$(modhead "${ind}.quad.fits" SCALE_U | gawk '{print $3}')
SCALE_L=$(modhead "${ind}.quad.fits" SCALE_L | gawk '{print $3}')

# convert from radians to arcmin...
SCALE_U_ARCMIN=$(echo "$SCALE_U * 180 / (a(1)*4) * 60" | bc -l)
SCALE_L_ARCMIN=$(echo "$SCALE_L * 180 / (a(1)*4) * 60" | bc -l)

#echo "Total stars: $sumstars"
#echo "Total quads: $sumquads"

IN=$(< $INFILE)
TMPFILE=$(mktemp /tmp/tmp.genprospectus.XXXXXX)
echo "cat <<END-GENPROSPECTUS" > $TMPFILE
echo "${IN}" >> $TMPFILE
echo "END-GENPROSPECTUS" >> $TMPFILE

#echo "echo Test" >> $TMPFILE

. $TMPFILE

rm $TMPFILE

